/*==============================
	01_schema.sql
	- Creación de tablas
================================*/

/*==========================================

	CREACIÓN DE LAS TABLAS DE DIMENSIONES

============================================*/


/* ========================================================================
	TABLA: dim_calendar
	
	Se usará para guardar la fecha de lanzamiento de cada juego del Dataset
	Se genera a partir de la columna release_date del CSV
==========================================================================*/
DROP TABLE IF EXISTS dim_calendar CASCADE;
CREATE TABLE dim_calendar (
	date_id DATE NOT NULL PRIMARY KEY,
	day_of_month SMALLINT NOT NULL,
	month_num SMALLINT NOT NULL CHECK(month_num BETWEEN 1 AND 12),	-- Me aseguro al hacer el CHECK que los meses válidos sean los que están comprendidos entre 1 y 12
	month_name VARCHAR(20) NOT NULL,
	quarter_num SMALLINT NOT NULL CHECK(quarter_num BETWEEN 1 AND 4),	--Los trimestres válidos esten comprendidos entre 1 y 4
	year_num SMALLINT NOT NULL,
	is_weekend BOOLEAN NOT NULL
);

/* ========================================================================
	TABLA: dim_genre
	
	Se usará para guardar el genero de cada juego del Dataset
	Se genera a partir de la columna genres del CSV
==========================================================================*/
DROP TABLE IF EXISTS dim_genre CASCADE;
CREATE TABLE dim_genre (
	genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre_name VARCHAR(50) NOT NULL UNIQUE
);

/* ========================================================================
	TABLA: dim_developer
	
	Se usará para guardar el desarrollador de cada juego del Dataset
	Se genera a partir de la columna developer del CSV
==========================================================================*/
DROP TABLE IF EXISTS dim_developer CASCADE;
CREATE TABLE dim_developer (
	developer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	developer_name VARCHAR(150) NOT NULL UNIQUE
);

/* ========================================================================
	TABLA: dim_publisher
	
	Se usará para guardar la distribuidora de cada juego del Dataset
	Se genera a partir de las columnas publishers del CSV
==========================================================================*/
DROP TABLE IF EXISTS dim_publisher CASCADE;
CREATE TABLE dim_publisher (
	publisher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	publisher_name VARCHAR(150) NOT NULL UNIQUE
);

/* ========================================================================
	TABLA: dim_platform
	
	Se usará para guardar las plataformas en las que puedes jugar un juego (Windows, Mac, Linux)
	Se genera a partir de las columnas windows, mac y linux del CSV, las cuales son booleanas
==========================================================================*/
DROP TABLE IF EXISTS dim_platform CASCADE;
CREATE TABLE dim_platform (
	platform_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	platform_name VARCHAR(20) NOT NULL UNIQUE
);


/*==========================================

	CREACIÓN DE LA TABLA DE HECHOS

============================================*/


/* ========================================================================
	TABLA: fact_games
	
	Será la tabla principal. Se usará para guardar los datos de los juegos
	Se genera a partir del propio CSV
==========================================================================*/
DROP TABLE IF EXISTS fact_games CASCADE;
CREATE TABLE fact_games (
	appid INT NOT NULL PRIMARY KEY,	--No le pongo que se generen automáticamente porque van a ser los propios que trae el CSV
	name VARCHAR(200) NOT NULL,
	release_date DATE NOT NULL,
	required_age SMALLINT NOT NULL,
	price NUMERIC(6,2) NOT NULL,
	dlc_count SMALLINT NOT NULL,
	metacritic_score SMALLINT NOT NULL,
	achievements INT NOT NULL,
	recommendations INT NOT NULL,
	positive_reviews INT NOT NULL,
	negative_reviews INT NOT NULL,
	average_playtime_forever INT NOT NULL,
	peak_ccu INT NOT NULL,	--Pico de jugadores simultáneos
	discount SMALLINT NOT NULL,
	owners_min INT NOT NULL,
	owners_max INT NOT NULL,
	publisher_id INT NOT NULL,
	
	-- Hago CONSTRAINT para saber exactamente qué ha fallado si hay un error
	CONSTRAINT fk_games_calendar FOREIGN KEY (release_date) REFERENCES dim_calendar (date_id),
	CONSTRAINT fk_games_publisher FOREIGN KEY (publisher_id) REFERENCES dim_publisher (publisher_id),
	CONSTRAINT chk_price CHECK (price >= 0),
	CONSTRAINT chk_discount CHECK (discount BETWEEN 0 AND 100),
	CONSTRAINT chk_metacritic CHECK (metacritic_score BETWEEN 0 AND 100),
	CONSTRAINT chk_required_age CHECK (required_age >= 0)
);


/*==========================================

	CREACIÓN DE LAS TABLAS PUENTE

============================================*/


/* ========================================================================
	TABLA: game_genre
	
	Se usará como tabla puente entre fact_games y dim_genre, puesto que un juego puede tener varios géneros
	y un genero puede pertenecer a varios juegos
==========================================================================*/
DROP TABLE IF EXISTS game_genre CASCADE;
CREATE TABLE game_genre (
	appid INT NOT NULL REFERENCES fact_games(appid),
	genre_id INT NOT NULL REFERENCES dim_genre(genre_id),
	
	PRIMARY KEY (appid, genre_id)
	
);

/* ========================================================================
	TABLA: game_developer
	
	Se usará como tabla puente entre fact_games y dim_developer, puesto que un juego puede tener varios desarrolladores
	y un desarrollador puede tener varios juegos
==========================================================================*/
DROP TABLE IF EXISTS game_developer CASCADE;
CREATE TABLE game_developer (
	appid INT NOT NULL REFERENCES fact_games(appid),
	developer_id INT NOT NULL REFERENCES dim_developer(developer_id),
	
	PRIMARY KEY (appid, developer_id)
);

/* ========================================================================
	TABLA: game_platform
	
	Se usará como tabla puente entre fact_games y dim_platform, puesto que un juego puede estar disponible
	en varrias plataformas y, una plataforma puede tener varios juegos
==========================================================================*/
DROP TABLE IF EXISTS game_platform CASCADE;
CREATE TABLE game_platform (
    appid INT NOT NULL REFERENCES fact_games(appid),
    platform_id INT NOT NULL REFERENCES dim_platform(platform_id),

    PRIMARY KEY (appid, platform_id)
);